[project]
name = "storynest-animated-stories"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.storynest-core]
path = "contracts/storynest-core.clar"
depends_on = []

[contracts.storynest-licensing]
path = "contracts/storynest-licensing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
